### ISSUE TITLE
something isn't right...

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#46]
I've just looked at some kinase inhibitors and noticed that all compounds and info loaded pre-Aug 25th has the same usan name and chembl ID?? Looks like only the newest data has gone in correctly into the instance i'm using?

**Comment by mnowotka** [comment]
I'm pretty sure that this problem is not related to the instance but probably the loading script. @revajk, can you take a look at this?

**Comment by Anneli15** [comment]
Also some issue with target dictionary in the description column (see screen shot)
Is it because there isn't a description for that target or because there is a script issue?

![screen shot 2015-09-08 at 12 31 20 pm](https://cloud.githubusercontent.com/assets/12811998/9733746/c77955c0-5625-11e5-8e15-4686138075bb.png)

**Comment by revajk** [comment]
I will look in to this. 

Reva

**Comment by revajk** [comment]
Anneli, Could you send me a screen shot for KI as well please? 

Thanks 
Reva

**Comment by mnowotka** [comment]
Reva, do you have access to VPN?

**Comment by revajk** [comment]
Yes.

**Comment by mnowotka** [comment]
In that case you don't need screenshots, you can log in and check yourself.

**Comment by revajk** [comment]
I know!!!  but I have my local version right . But I can’t figure out in sark which are kinase Inhibitors. To know which compound to look for.

**Comment by mnowotka** [comment]
You have a full access to both versions, you can even scp both sqlite files make a sql dumps out of them and compare. But if the screenshot will help you, Anneli can make one for you.

**Comment by revajk** [comment]
Thanks!Anneli, I might have to deploy again to sark. My local version is good. I think I realised after I deployed to sark, and haven’t fixed in sark.

Will let you know once  I deploy.

Reva.

**Comment by revajk** [comment]
Anneli, Sorry, I have problem with few of mine as well. I will check in KI in detail and will let you know

**Comment by Anneli15** [comment]
Sorry was at lunch, here is screen shots. It's not only KI:s though, seems anything loaded before 25th.

![screen shot 2015-09-08 at 12 17 08 pm](https://cloud.githubusercontent.com/assets/12811998/9734879/8965bd24-562e-11e5-9ec0-a38929e24050.png)

**Comment by mnowotka** [comment]
@revajk any progress on that? I would appreciate some ETA here.

**Comment by revajk** [comment]
Have got the target dictionary listings sorted. But still looking on the KI USAN names.

**Comment by mnowotka** [comment]
Thanks. Can you deploy what you have?

**Comment by revajk** [comment]
I think I am near to fixing the KI usan name as well  I shall deploy them together if that’s okie.

**Comment by mnowotka** [comment]
If it will be deployed today, it's OK.

**Comment by revajk** [comment]
Hi both, I have deployed to the development server. (http://sark.ebi.ac.uk:7001/idg/ http://sark.ebi.ac.uk:7001/idg/) I am going to deploy to the production.

**Comment by mnowotka** [comment]
Perfect! Thank you Reva. Please let us know when this is up and running.

**Comment by Anneli15** [comment]
Reva, it is still unfortunately wrong. The name has changed and chembl ID is different but is still the same for all compounds loaded in August. See screen shot below. Not sure what's going on.

![screen shot 2015-09-08 at 5 07 21 pm](https://cloud.githubusercontent.com/assets/12811998/9740370/51688f5a-564c-11e5-9a42-cc575f56ac52.png)

There are some compound with todays load date that look OK, haven't checked them all but at least they have a individual names and chembl IDs

**Comment by revajk** [comment]
Sorry I remembered you saying they are KI. But these seems to be NR compounds.  I shall look through everything then.

**Comment by Anneli15** [comment]
It is basically everything loaded in August. There is only a page and a half of entries (mixed targets, not KIs) that have changed today, the rest are all wrong.

**Comment by mnowotka** [comment]
Is this issue resolved?
