### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#58]
I get an error 500 when trying to save new compound in the molecular dictionary

**Comment by revajk** [comment]
I get them only when  I am trying to use CHEMBL-lookup is that the same case for you too?

**Comment by Anneli15** [comment]
I've just tested it and I get 500 error when trying to add chembl ID only and then save. I added the compound name and phase and saved and that was OK. Goiung in and adding Chembl ID after seemed to work too....?

**Comment by Anneli15** [comment]
Have checked and the chembl look up didn't work for the compound added. So no inchl key or anything else was added from Chembl. So something is wrong with the look up  guess.

**Comment by Anneli15** [comment]
CHEMBL41306 is an example of chembl drug with no name. Only info is structure (inchlkey) and pubmed ID.

**Comment by revajk** [comment]
Thanks Anneli. Got it fixed. Will try to release them before I leave other wise i will push it live later in the evening. 
The server is still up  and running. Since there is no change of data I might not have to turn it off.

**Comment by revajk** [comment]
Should work fine now.

**Comment by revajk** [comment]
The Chemspi lookup should work fine, other than save and continue. I am still working on it.
Other than that both chemo; and chemspi lookup should work fine now. 

Thanks
Reva.

**Comment by mnowotka** [comment]
@Anneli15 - can you check if this fixes the 500 error problem?

**Comment by Anneli15** [comment]
I can save compounds either with Chembl ID or inchl key. Not sure the look-up works though or at least there system doesn't actually add any information to the entry or is it not suppose to at this stage? The other slightly awkward thing is adding more info to a compound. I know I asked for alphabetical order in the boxes for mechanism etc but now as I add a compound and want to edit, I have to go back and look for it with the name in the search box to get the entry and be able to add more details like mechanism, company etc. Not sure how to change this, I did raise this before in issue 51?

**Comment by revajk** [comment]
Only the CHEMBL lookup will pull you all the other information like synonym name and ATC information. Chempsi lookup should fetch just structural information along with the ‘Common-name’ or the molecule name if its a new entry. Champs don’t have any other  information that we need

. If you don’t see any of your added compounds at the top you can always order them by date loaded - to desc so that your new addition would be on top.  As far as I understand, I think I have to order them in molecule dictionary to have them ordered in mechanism.

Reva.

**Comment by Anneli15** [comment]
I added CHEMBL604710 and no information was retrieved as far as I can see?

**Comment by Anneli15** [comment]
Ok so structure key works and fetches data from Chemspider (I think). However, the same compound is there now twice as VCPMZDWBEWTGNW-UHFFFAOYSA-N (1-[4-(Diphenylmethyl)-1-piperazinyl]-3,3-diphenyl-1-propanone in compound name box) is the same as CHEMBL604710.

**Comment by Anneli15** [comment]
So if I add a chembl id, what data should this fetch if I press "save and edit"?

**Comment by revajk** [comment]
If available It should get you structure, synonym, atc along with molecule dictionary.

**Comment by revajk** [comment]
I am looking in to this att he moment. Will let you know what is wrong and let you know as soon as I finish.

**Comment by revajk** [comment]
Chembl lookup is working fine now. The reason it wasn’t getting the synonym information is because the Research_code in synonym_types had a trailing white space at the end and it couldn’t match the synonym type. 

Its all fixed now. 

And Regarding, the CHEMBL604710 being added twice. I can’t see them added twice.

The chembl604710 lookup haven’t got a molecule name and the 1-[4-(Diphenylmethyl)-1-piperazinyl]-3,3-diphenyl-1-propanone doesn’t have a chembl-id. 

IT wouldn’t be able to figure out the two compounds are same unless it has a common Moleculename .

Hope that helps,

**Comment by Anneli15** [comment]
I have removed the duplicate entries, used the compound to test the system. tried to add CHEMBL604710 again but it still doesn't fetch anything from chembl, not sure why it's not working for me?

**Comment by revajk** [comment]
Compound you tested Same?

**Comment by Anneli15** [comment]
yes. I entered it first with chembl id but as it didn't bring back any structural data (or synonyms/names) I tried using the inchl key. This worked but like I said, only look up infer from cehmspider. So the system saved the same compound twice as the info didn't overlap (=chembl lookup didn't fetch the inchl key)

**Comment by revajk** [comment]
What version are you seeing? 62?

**Comment by Anneli15** [comment]
V60

**Comment by Anneli15** [comment]
now v62

**Comment by Anneli15** [comment]
Looks like it's working now that I see the new version.

**Comment by revajk** [comment]
Super !
